"""Add owner table

Revision ID: 91c84538fe11
Revises: 206b8d0a7849
Create Date: 2019-06-28 17:29:59.268839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c84538fe11'
down_revision = '206b8d0a7849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('pup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pup_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_column('puppies', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('owner', sa.TEXT(), nullable=True))
    op.drop_table('owners')
    # ### end Alembic commands ###
